### PR TITLE
Large improvement pack

### LINKED ISSUE #184: https_dns_proxy + dnsmasq + systemd-resolved dnssec failure
I'm facing a problem with my DNS resolution chain that lead to dnssec validation failures on some names:

My raspberry pi (192.168.0.254 in the following examples) runs https_dns_proxy on port 5053 to connect to Cloudflare's DOH service. dnsmasq uses the proxy service on port 5053 as upstream DNS server and offers a classic DNS service for the internal network on port 53. So far so normal.

One of my computers (192.168.0.2, aka "grey") running Gentoo ended up using systemd-resolved. I guess this got pushed through systemd defaults somewhen. Via dhcp it learns to talk to said dnsmasq on 192.168.0.254:53. This mostly works, except that some domains fail to resolve, with systemd-resolved complaining abnout dnssec:

```
$ dig bmeia.gv.at

; <<>> DiG 9.18.31 <<>> bmeia.gv.at
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 7213
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;bmeia.gv.at.                   IN      A

;; Query time: 341 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Sat May 03 15:53:27 EAT 2025
;; MSG SIZE  rcvd: 40

$ resolvectl query bmeia.gv.at
bmeia.gv.at: resolve call failed: DNSSEC validation failed: no-signature (Network Error)

```

journalctl -f has the following complaint:

```
May 03 15:52:37 grey systemd-resolved[127851]: [🡕] DNSSEC validation failed for question bmeia.gv.at IN DNSKEY: no-signature
May 03 15:52:37 grey systemd-resolved[127851]: [🡕] DNSSEC validation failed for question bmeia.gv.at IN A: no-signature
May 03 15:52:37 grey systemd-resolved[127851]: [🡕] DNSSEC validation failed for question bmeia.gv.at IN AAAA: no-signature
```

Almost all other domains work fine, including dnssec validation:

```
$ resolvectl query go.dnscheck.tools
go.dnscheck.tools: 2a01:4f8:1c1e:84c3::1       -- link: wlan0
                   116.203.95.251              -- link: wlan0

-- Information acquired via protocol DNS in 1.2003s.
-- Data is authenticated: yes; Data was acquired via local or encrypted transport: no
-- Data from: network
stefan@grey ~ $ resolvectl query badsig.go.dnscheck.tools
badsig.go.dnscheck.tools: resolve call failed: DNSSEC validation failed: invalid (DNSSEC Bogus: failed to verify badsig.go.dnscheck.tools. A: using DNSKEY ids = [35243])

```

The two I found were and bmeia.gv.at and www.thecitizen.co.tz . There might of course be more.

Doing *one* of the following works around the issue:

* Set DNSSEC=no in /etc/systemd/resolved.conf, but this obviously breaks dnssec.
* Cut out https_dns_proxy and make dnsmasq talk directly to e.g. 1.1.1.1 port 53 (see the footnote below though)
* Cut out dnsmasq and let systemd-resolved talk to https_dns_proxy directly
* Cut out systemd-resolved and let the glibc resolver talk to dnsmasq->https_dns_proxy->cloudflare

So the following chain fails:
dig -> systemd-resolved -> dnsmasq -> https_dns_proxy -> cloudflare

The following chains work:
* dig -> systemd-resolved -> dnsmasq -> cloudflare
* dig -> systemd-resolved -> https_dns_proxy -> cloudflare
* dig -> dnsmasq -> https_dns_proxy -> cloudflare

The first two of those also show "Data is authenticated: yes" for bmeia.gv.at when I use resolvectl. www.thecitizen.co.tz does not seem to have a dnssec signature. The last one (without systemd-resolved) shows a dnssec record in dig +dnssec for bmeia.gv.at.

Other systems I am using (Android, Mac OS, Linux without systemd-resolved) work fine.

I built https-dns-proxy from source, git commit 0e074b40f3. For the examples here I ran it with `./https_dns_proxy -b 192.168.0.1,1.0.0.1 -r https://cloudflare-dns.com/dns-query -4 -l - -a 0.0.0.0 -p 5053` as root. The normal startup service invokes it as unprivileged user and only allows connections from 127.0.0.1 of course.

Footnote: Any unencrypted DNS traffic is intercepted by my ISP and answered by its own servers to implement a dumb filter to semi-satisfy legal requirements. I don't care too much about the filtering, but the ISP's DNS server is unresponsive every now and then, making my entire connection unstable for stupid reasons. Hence the use of DNS over HTTPS.

### LINKED ISSUE #186: TCP support
I'm wondering if https-dns-proxy will consider supporting TCP. 

I am trying to have a setup like this:

https-dns-proxy <---> dnsmasq <---> DNS over TLS proxy <---> My devices

It is quite easy to terminate TCP with TLS with nginx once acme is already setup, however, dnsmasq has a quirk where if you query via TCP, it will also only query the upstream via TCP. Since https-dns-proxy does not support TCP, it just fails, unless the domain has already been queried via UDP and cached before the TCP request to dnsmasq.

I'm looking at implementing a DoT proxy because most browsers do not use ESNI if DNS is not encrypted. https-dns-proxy is very lightweight, almost gets the job done and if it adds TCP support, will allow for a very lightweight DoT setup on LAN with nginx while preventing third parties snooping on the SNI.

This behavior also affects usage regardless of DoT, any application querying dnsmasq via TCP with https-dns-proxy as the only upstream for dnsmasq will fail.

### LINKED ISSUE #189: A persistent timeout occurs when the network changes (static IP changed or PPPoE reconnected).
# What happened

When using `https-dns-proxy` on OpenWrt, I encountered a troubling issue: every time I reconnect the WAN interface using the PPPoE protocol, the DNS often becomes unresponsive. Specifically, both `dig @router` and `dig @127.0.0.1 -p 5053` (with 5053 being the listening port of `https-dns-proxy`) result in a timeout.

I’ve investigated this issue in depth and found that it can be easily reproduced on Ubuntu 24.04 as well.

# How to reproduce

1. Install Ubuntu 24.04 (I used the Desktop version).
2. Configure the network to use a static IP address. E.g. `192.168.9.100`
3. Open two terminal windows and run the following commands in each:

```bash
./https_dns_proxy -r https://dns.alidns.com/dns-query -p 5053 -4 -m 10 -vvv
```

```bash
while true; do dig 1.2.3.4.sslip.io @127.0.0.1 -p 5053 ; sleep 1;  done
```

4. Change the static IP address, for example, to `192.168.9.101`.

Image

5. You can observe the output like this (please use this [PR](https://github.com/aarond10/https_dns_proxy/pull/188) to fix logging):

```
[D] 1749047614.457423 https_client.c:219 E50A: * Operation timed out after 5004 milliseconds with 0 bytes received
[D] 1749047614.457494 https_client.c:219 E50A: * Connection #0 to host dns.alidns.com left intact
[D] 1749047614.457508 https_client.c:620 Released used io event: 0x7ffe22471f90
[W] 1749047614.457520 https_client.c:360 E50A: curl request failed with 28: Timeout was reached
[W] 1749047614.457537 https_client.c:362 E50A: curl error message: Operation timed out after 5004 milliseconds with 0 bytes received
[W] 1749047614.457548 https_client.c:376 E50A: Connecting and sending request to resolver was successful, but no response was sent back
[D] 1749047614.457555 https_client.c:446 E50A: CURLINFO_NUM_CONNECTS: 0
[D] 1749047614.457559 https_client.c:458 E50A: CURLINFO_EFFECTIVE_URL: https://dns.alidns.com/dns-query
[D] 1749047614.457568 https_client.c:495 E50A: Times: 0.000033, 0.000000, 0.000000, 0.000143, 0.000000, 5.004893
[I] 1749047614.457583 https_client.c:517 E50A: Response was faulty, skipping DNS reply
[D] 1749047614.457588 main.c:83 Received response for id: E50A, len: 0
[D] 1749047614.457627 main.c:112 Received request for id: E50A, len: 57
[D] 1749047614.457649 https_client.c:261 E50A: Requesting HTTP/2
[D] 1749047614.457678 https_client.c:219 E50A: * RESOLVE dns.alidns.com:443 - old addresses discarded
[D] 1749047614.457698 https_client.c:219 E50A: * Added dns.alidns.com:443:223.5.5.5,223.6.6.6 to DNS cache
[D] 1749047614.457747 https_client.c:219 E50A: * Found bundle for host: 0x559ad0c37f30 [can multiplex]
[D] 1749047614.457762 https_client.c:219 E50A: * Re-using existing connection with host dns.alidns.com
[D] 1749047614.457806 https_client.c:219 E50A: * [HTTP/2] [27] OPENED stream for https://dns.alidns.com/dns-query
[D] 1749047614.457816 https_client.c:219 E50A: * [HTTP/2] [27] [:method: POST]
[D] 1749047614.457823 https_client.c:219 E50A: * [HTTP/2] [27] [:scheme: https]
[D] 1749047614.457828 https_client.c:219 E50A: * [HTTP/2] [27] [:authority: dns.alidns.com]
[D] 1749047614.457833 https_client.c:219 E50A: * [HTTP/2] [27] [:path: /dns-query]
[D] 1749047614.457854 https_client.c:219 E50A: * [HTTP/2] [27] [user-agent: https_dns_proxy/0.3]
[D] 1749047614.457860 https_client.c:219 E50A: * [HTTP/2] [27] [accept: application/dns-message]
[D] 1749047614.457866 https_client.c:219 E50A: * [HTTP/2] [27] [content-type: application/dns-message]
[D] 1749047614.457872 https_client.c:219 E50A: * [HTTP/2] [27] [content-length: 57]
[D] 1749047614.457961 https_client.c:219 E50A: > POST /dns-query HTTP/2
[D] 1749047614.457975 https_client.c:219 E50A: > Host: dns.alidns.com
[D] 1749047614.457980 https_client.c:219 E50A: > User-Agent: https_dns_proxy/0.3
[D] 1749047614.457984 https_client.c:219 E50A: > Accept: application/dns-message
[D] 1749047614.458045 https_client.c:219 E50A: > Content-Type: application/dns-message
[D] 1749047614.458057 https_client.c:219 E50A: > Content-Length: 57
[D] 1749047614.458067 https_client.c:170 E50A: > 0000: e5 0a 01 20 00 01 00 00 00 00 00 01 01 31 01 32 ... .........1.2
[D] 1749047614.458077 https_client.c:170 E50A: > 0010: 01 33 01 34 05 73 73 6c 69 70 02 69 6f 00 00 01 .3.4.sslip.io...
[D] 1749047614.458087 https_client.c:170 E50A: > 0020: 00 01 00 00 29 04 d0 00 00 00 00 00 0c 00 0a 00 ....)...........
[D] 1749047614.458102 https_client.c:170 E50A: > 0030: 08 57 d6 2c 4d ff 74 cb 32                      .W.,M.t.2
[D] 1749047614.458122 https_client.c:633 Reserved new io event: 0x7ffe22471f90

...about 5s later...

[D] 1749047619.461386 https_client.c:219 E50A: * Operation timed out after 5003 milliseconds with 0 bytes received
[D] 1749047619.461450 https_client.c:219 E50A: * Connection #0 to host dns.alidns.com left intact
[D] 1749047619.461461 https_client.c:620 Released used io event: 0x7ffe22471f90
[W] 1749047619.461471 https_client.c:360 E50A: curl request failed with 28: Timeout was reached
[W] 1749047619.461476 https_client.c:362 E50A: curl error message: Operation timed out after 5003 milliseconds with 0 bytes received
[W] 1749047619.461483 https_client.c:376 E50A: Connecting and sending request to resolver was successful, but no response was sent back
[D] 1749047619.461488 https_client.c:446 E50A: CURLINFO_NUM_CONNECTS: 0
[D] 1749047619.461491 https_client.c:458 E50A: CURLINFO_EFFECTIVE_URL: https://dns.alidns.com/dns-query
[D] 1749047619.461498 https_client.c:495 E50A: Times: 0.000058, 0.000000, 0.000000, 0.000400, 0.000000, 5.003270
[I] 1749047619.461509 https_client.c:517 E50A: Response was faulty, skipping DNS reply
[D] 1749047619.461512 main.c:83 Received response for id: E50A, len: 0
[D] 1749047619.462845 main.c:112 Received request for id: E50A, len: 57
[D] 1749047619.462857 https_client.c:261 E50A: Requesting HTTP/2
[D] 1749047619.462870 https_client.c:219 E50A: * RESOLVE dns.alidns.com:443 - old addresses discarded
[D] 1749047619.462873 https_client.c:219 E50A: * Added dns.alidns.com:443:223.5.5.5,223.6.6.6 to DNS cache
[D] 1749047619.462890 https_client.c:219 E50A: * Found bundle for host: 0x559ad0c37f30 [can multiplex]
[D] 1749047619.462894 https_client.c:219 E50A: * Re-using existing connection with host dns.alidns.com
[D] 1749047619.462907 https_client.c:219 E50A: * [HTTP/2] [29] OPENED stream for https://dns.alidns.com/dns-query
[D] 1749047619.462911 https_client.c:219 E50A: * [HTTP/2] [29] [:method: POST]
[D] 1749047619.462912 https_client.c:219 E50A: * [HTTP/2] [29] [:scheme: https]
[D] 1749047619.462913 https_client.c:219 E50A: * [HTTP/2] [29] [:authority: dns.alidns.com]
[D] 1749047619.462915 https_client.c:219 E50A: * [HTTP/2] [29] [:path: /dns-query]
[D] 1749047619.462916 https_client.c:219 E50A: * [HTTP/2] [29] [user-agent: https_dns_proxy/0.3]
[D] 1749047619.462921 https_client.c:219 E50A: * [HTTP/2] [29] [accept: application/dns-message]
[D] 1749047619.462922 https_client.c:219 E50A: * [HTTP/2] [29] [content-type: application/dns-message]
[D] 1749047619.462924 https_client.c:219 E50A: * [HTTP/2] [29] [content-length: 57]
[D] 1749047619.462954 https_client.c:219 E50A: > POST /dns-query HTTP/2
[D] 1749047619.462957 https_client.c:219 E50A: > Host: dns.alidns.com
[D] 1749047619.462958 https_client.c:219 E50A: > User-Agent: https_dns_proxy/0.3
[D] 1749047619.462959 https_client.c:219 E50A: > Accept: application/dns-message
[D] 1749047619.462960 https_client.c:219 E50A: > Content-Type: application/dns-message
[D] 1749047619.462961 https_client.c:219 E50A: > Content-Length: 57
[D] 1749047619.462963 https_client.c:170 E50A: > 0000: e5 0a 01 20 00 01 00 00 00 00 00 01 01 31 01 32 ... .........1.2
[D] 1749047619.462965 https_client.c:170 E50A: > 0010: 01 33 01 34 05 73 73 6c 69 70 02 69 6f 00 00 01 .3.4.sslip.io...
[D] 1749047619.462967 https_client.c:170 E50A: > 0020: 00 01 00 00 29 04 d0 00 00 00 00 00 0c 00 0a 00 ....)...........
[D] 1749047619.462969 https_client.c:170 E50A: > 0030: 08 57 d6 2c 4d ff 74 cb 32                      .W.,M.t.2
[D] 1749047619.462974 https_client.c:633 Reserved new io event: 0x7ffe22471f90
```

# Analysis

It is clear that using the `-m` parameter (CURLOPT_MAXAGE_CONN) does not alleviate the problem. As long as the `dig` continues running, the timeout can persist for a long time (I tested for 10 minutes and it was still timing out).

This issue is likely related to HTTP/2 TCP connection reuse. When forcing HTTP/1.1 with the `-x` option, the timeout only lasts for a short period.

I suspect this issue may be related to [TCP half-open connections](https://en.wikipedia.org/wiki/TCP_half-open). In the reproduction steps, changing to a different IP address rather than simply toggling the ethernet interface is necessary.

# Possible Solutions

Replacing `CURLOPT_MAXAGE_CONN` with [`CURLOPT_MAXLIFETIME_CONN`](https://curl.se/libcurl/c/CURLOPT_MAXLIFETIME_CONN.html) could resolve this issue.

According to [this function](https://github.com/curl/curl/blob/e67a500841c019f8ab8102f4f8525a302f425cdb/lib/url.c#L673-L704), `CURLOPT_MAXAGE_CONN` compares `conn->created` with the current time, which helps avoid the issue where `conn->lastused` gets updated by "send-only" activity.

# Related issue

## https://github.com/aarond10/https_dns_proxy/issues/106

This issue is similar to the problem at hand and provides a temporary workaround by restarting the service on OpenWrt. However, I believe this solution is not ideal.

## https://github.com/curl/curl/issues/3132

This issue includes an in-depth discussion of the problem and suggests that using HTTP/2 PING frames might be a potential solution—though. But I haven't seen a concrete implementation provided.

### PR DESCRIPTION
**Pull request by baranyaib90**
Hi Aaron,
I hope you are doing well! I suppose you won't like me now. I have a lot of things for review.
Content list:

1. TCP support to fix #186 
2. UDP reply truncation feature to fix #184
3. Code quality stuff: more compiler warnings and warning fixes
4. c-ares API modernization
5. Reset HTTPS connection to avoid half-open TCP problems to fix #189 
6. systemd improvements (mostly for my Ubuntu server)
7. Version bump (I guess it is time)

@stangri it I may ask, please remove file https://github.com/openwrt/packages/blob/master/net/https-dns-proxy/patches/010-cmakelists-remove-cflags.patch if you would uplift the OpenWRT package after this pull request would be merged. I have compiled the OpenWRT package myself and I have not met any warnings. If there would be, please let me know. Thanks!

Take your time.
Best regards,
Balázs

### CODE REVIEW

**Comment by baranyaib90** [comment]
Ps.: I was testing my changes for 2 months and I have even asked issue reporters to test with proxy built from my repo if it works well. You can check the conversation on bug reports. I suppose it will be good enough.

**Comment by aarond10** [comment]
bugbot run

**Comment by baranyaib90** [comment]
I have fixed the bugbot findings. Before merge lets squash the fixups.
The sin_port tricking was intentional, since the port is on the same memory area both in sockaddr_in and sockaddr_in6 structs. But lets be safe then.

File: src/dns_server.c [hunk 1]
```diff
@@ -1,95 +1,78 @@
...
 
-  char *buf = (char *)calloc(1, REQUEST_MAX + 1);
-  if (buf == NULL) {
-    FLOG("Out of mem");
-  }
-  struct sockaddr_storage raddr;
-  /* recvfrom can write to addrlen */
-  socklen_t tmp_addrlen = d->addrlen;
-  ssize_t len = recvfrom(w->fd, buf, REQUEST_MAX, 0, (struct sockaddr*)&raddr,
+  char tmp_buf[UINT16_MAX];  // stack buffer for largest UDP packet to support EDNS
```
Comment (aarond10) [inline src/dns_server.c:46]: I worry a little about this. It's probably OK but might blow up on some small systems with limited stack space.
We copy it into a heap allocated buffer anyway, so what about 
```
char *dns_req = (char *)malloc(UINT16_MAX);
recvfrom(...);
...
dns_req = (char *)realloc(dns_req, len);
if (dns_req == NULL) { ... }
```

File: src/dns_server.c [hunk 2]
```diff
@@ -99,9 +82,127 @@ void dns_server_init(dns_server_t *d, struct ev_loop *loop,
...
+  }
+  ares_dns_record_destroy(dnsrec);
+  if (udp_size < DNS_SIZE_LIMIT) {
+    DLOG("%04hX: EDNS0 UDP buffer size %u overruled to %d", tx_id, udp_size, DNS_SIZE_LIMIT);
+    return DNS_SIZE_LIMIT;  // RFC6891 4.3 "Values lower than 512 MUST be treated as equal to 512."
+  }
+  return udp_size;
+}
+
+static void truncate_dns_response(char *buf, size_t *buflen, const uint16_t size_limit) {
```
Comment (aarond10) [inline src/dns_server.c:113]: Oh wow!

File: src/dns_server.c (hunk 1 above)
Comment (baranyaib90) [reply src/dns_server.c:46]: Even on openwrt the stack limit is 8MB per thread. Stack size grows only by usage. For my taste 64k is not a huge deal and I would not mess with heap for temporary buffers. Also I would not reserve more on heap (and shrik later) to avoid heap fragmentation. So I'm not expecting any issues with this.
Anyway: I will think about this.

**Comment by baranyaib90** [comment]
I have been thinking about the stack buffer and I would like to keep it. My compromise is to lower the size from 64k to 4k. Before the limit was 1500 byte, so this should be more than enough. Now it will be logged if it was not enough. In case of TCP this does not cause issue, just the read callback will be called multiple times. I hope that this is acceptable by you, if not, then please let me know your proposal.

**Comment by aarond10** [comment]
That sounds fine to me. I haven't used realloc much in the past and I like
the idea that we are in control of the semantics of buffer management
rather than using some niche libc call.

**Comment by baranyaib90** [comment]
Advanced tab sounds great!

Resolver specific:

-  HTTP/3 (QUIC) option if supported by openwrt libcurl
- max_idle_time, since it depends on resolver server configuration

Other options are more like global.

**Comment by baranyaib90** [comment]
Nice page. The only thing I'm missing is the settings value range. e.g. `(Default: 0, Disabled: 0, Min: 1, Max: 3600)`
Obviously it is up to you to include them or not.

**Comment by stangri** [comment]
@baranyaib90 on 24.10.2 (x86-64) I got the following in dmesg:
```
[2379127.133000] traps: https-dns-proxy[18318] trap divide error ip:404bde sp:7ffeae0f68d0 error:0 in https-dns-proxy[403000+7000]
[2380210.516055] traps: https-dns-proxy[19980] trap divide error ip:404bde sp:7fff96e5f0d0 error:0 in https-dns-proxy[403000+7000]
[2394799.142337] traps: https-dns-proxy[22169] trap divide error ip:404bde sp:7ffcb278bcd0 error:0 in https-dns-proxy[403000+7000]
```

**Comment by baranyaib90** [comment]
It looks like a divide by 0 error, but the location is unclear to me. If you can reproduce the issue, could you run the proxy with debug logs? I would need the last ~1000 logs of the stopped proxy.

**Comment by stangri** [comment]
Sorry, clarification: I was looking for something else at dmesg and saw these, I don't know how/when it happened, I'll try to reproduce but not sure if i can.

**Comment by baranyaib90** [comment]
Hi @stangri, are there any new crashes mentioned in dmesg since?
I'm planning to raise the pull request soon.

**Comment by stangri** [comment]
Hey @baranyaib90, nothing in dmesg. Your change either worked or at least did no harm, so I'd vote in favour of PR/merging this code. I'll create PR for the OpenWrt package once your code is merged in this repo.
